default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: <%= ENV.fetch('OMNIBIRD_BACKEND_DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('OMNIBIRD_BACKEND_DATABASE_USERNAME') %>
  password: <%= ENV.fetch('OMNIBIRD_BACKEND_DATABASE_PASSWORD') %>

development:
  <<: *default
  database: omnibird_backend_development

test:
  <<: *default
  database: omnibird_backend_test

production:
  <<: *default
  database: omnibird_backend_production
